// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgvSMW6E0VIlvSj8_2PInlo_9cx3EF7Ag',
    appId: '1:18825890802:web:5a72d2c5d14c8e3422396b',
    messagingSenderId: '18825890802',
    projectId: 'lorry-app-user',
    authDomain: 'lorry-app-user.firebaseapp.com',
    storageBucket: 'lorry-app-user.firebasestorage.app',
    measurementId: 'G-0XT08J6LY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzdkVVYocSPo4tu1Vm951tdCHmgMnto2o',
    appId: '1:18825890802:android:c100b940493dbbb822396b',
    messagingSenderId: '18825890802',
    projectId: 'lorry-app-user',
    storageBucket: 'lorry-app-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdxJfJRZe9TYJwQ99asOrJQ0HbnutGbcM',
    appId: '1:18825890802:ios:66afe84dcaf11a2022396b',
    messagingSenderId: '18825890802',
    projectId: 'lorry-app-user',
    storageBucket: 'lorry-app-user.firebasestorage.app',
    iosBundleId: 'com.rifanasherin.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdxJfJRZe9TYJwQ99asOrJQ0HbnutGbcM',
    appId: '1:18825890802:ios:946f0a6d08c7901f22396b',
    messagingSenderId: '18825890802',
    projectId: 'lorry-app-user',
    storageBucket: 'lorry-app-user.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgvSMW6E0VIlvSj8_2PInlo_9cx3EF7Ag',
    appId: '1:18825890802:web:5c9e8855ce7f8b6422396b',
    messagingSenderId: '18825890802',
    projectId: 'lorry-app-user',
    authDomain: 'lorry-app-user.firebaseapp.com',
    storageBucket: 'lorry-app-user.firebasestorage.app',
    measurementId: 'G-8QPFSTG713',
  );
}
